#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add_patient:
    path: /add_patient
    controller: 'App\Controller\PatientController::addPatient'

list_patients:
    path: /list_patients
    controller: 'App\Controller\PatientController::listPatients'

first_page:
    path: /firstpage
    controller: 'App\Controller\MedecinController::firstPageAction'
